name: Build React Native Android APK

on:
  push:
    branches: [ main ] # Push tetikleyici (isteğe bağlı, isterseniz kaldırabilirsiniz)
  pull_request:
    branches: [ main ] # Pull request tetikleyici (isteğe bağlı)
  workflow_dispatch: # Manuel tetikleyici

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/my-release-key.keystore

    - name: Install npm dependencies
      run: npm install

    - name: Create Android Bundle
      run: |
        npx react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 7
